/**
 * v53 — web_search display + post-search silence fixes.
 *
 * The reported bug: "web search fails to display results and takes a long time".
 * Reproduced live against LM Studio (qwen3-27b): after the web_search tool result
 * landed, the model's NEXT turn either chained into fetch_url (~50s of prompt
 * processing per hop) or returned an EMPTY stream (whole reply spent on internal
 * reasoning). The app then nudged ("Please summarize…") and looped — forever.
 * Meanwhile the only thing painted was a "sources" card that listed TITLES ONLY,
 * so to the user it read as: search ran, nothing displayed, no summary ever.
 *
 * Fixes under test:
 *   1. agentTools web_search returns COMPACT result text (snippets capped at 200
 *      chars) and a nudge that tells the model to answer NOW — not chain fetch_url.
 *   2. displayWebSearchResults renders each source with its LINKED title, URL and
 *      snippet (not titles only), for both the new compact shape and the legacy one.
 *   3. The chat loop's silent-turn nudge is BOUNDED: after 3 consecutive empty
 *      replies it ends the run with an honest note instead of spinning forever.
 *   4. Code Mode timeline shows the actual retrieved content for web_search /
 *      fetch_url (not a KV dump) and counts sources in the row summary.
 */
'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

let JSDOM;
try { ({ JSDOM } = require('jsdom')); } catch (e) { /* optional dep */ }

// ── 1. agentTools: v54 deep-research report (pages read in full, not snippets) ────

const { executeAgentChatTool } = (() => {
    delete require.cache[require.resolve('../src/renderer/modes/agentTools.js')];
    return require('../src/renderer/modes/agentTools.js');
})();
const wt = require('../src/shared/webTools.js');

// The REAL report shape, generated by the engine's own builder (what main sends over IPC).
function deepReportFixture() {
    const results = [
        { title: 'First Source', url: 'https://a.test/page', snippet: 'short snippet' },
        { title: 'Second Source', url: 'https://b.test/', snippet: 'another snippet' }
    ];
    const pages = [{ index: 0, url: results[0].url, title: results[0].title, truncated: false, summary: 'The first source explains the topic in detail, with numbers and names.', keyFacts: ['The key fact is that 42% of users prefer it (2026).'] }];
    return { query: 'q', results, pagesRead: pages.length, report: wt.buildResearchReport('q', results, pages) };
}

test('v54: web_search returns the deep-research report (findings, not capped snippets)', async () => {
    const deps = { api: { invoke: async () => deepReportFixture() } };
    const out = await executeAgentChatTool('web_search', { query: 'q' }, deps);
    assert.ok(out.startsWith('DEEP RESEARCH REPORT'), 'report header first');
    assert.ok(out.includes('WHAT I LEARNED FROM THIS PAGE:'), 'learned content present');
    assert.ok(out.includes('- The key fact is that 42% of users prefer it (2026).'), 'key facts present');
    assert.ok(out.includes('SOURCE 2: Second Source — another snippet'), 'snippet-only sources still listed');
});

test('v54: the report nudge demands a detailed natural-language answer, no bare snippets', async () => {
    const deps = { api: { invoke: async () => deepReportFixture() } };
    const out = await executeAgentChatTool('web_search', { query: 'q' }, deps);
    assert.ok(out.includes('[SYSTEM NUDGE]'));
    assert.match(out, /detailed, complete report/i, 'must demand a detailed full report');
    assert.match(out, /natural language/i, 'report must be natural language');
});

test('web_search error + zero-hit paths unchanged (contract from v47.8)', async () => {
    const errOut = await executeAgentChatTool('web_search', { query: 'q' }, { api: { invoke: async () => ({ error: 'Search failed: 503' }) } });
    assert.ok(errOut.startsWith('Web search failed:') && errOut.includes('503'));
    const zeroOut = await executeAgentChatTool('web_search', { query: 'q' }, { api: { invoke: async () => ({ results: [], report: null }) } });
    assert.ok(zeroOut.startsWith('No web results found'));
});

// ── 2. displayWebSearchResults: real content, not titles only ─────────────────

const APP_SRC = fs.readFileSync(path.join(__dirname, '..', 'src', 'renderer', 'app.js'), 'utf8');

/** Extract a top-level `function NAME(...) {...}` from app.js (ends at first column-0 `}`). */
function extractFunction(src, name) {
    const start = src.indexOf(`function ${name}(`);
    assert.notEqual(start, -1, `${name} must exist in app.js`);
    const endMarker = '\n}\n';
    const end = src.indexOf(endMarker, start);
    assert.notEqual(end, -1, `end of ${name}`);
    return src.slice(start, end + 2); // include the closing "}"
}

function makeDisplayFn(dom) {
    const messagesDiv = dom.window.document.createElement('div');
    dom.window.document.body.appendChild(messagesDiv);
    let scrolled = false;
    const factory = new dom.window.Function(
        'messagesContainer', 'scrollMessagesToLatest',
        extractFunction(APP_SRC, 'displayWebSearchResults') + '\nreturn displayWebSearchResults;'
    );
    return { fn: factory(messagesDiv, () => { scrolled = true; }), messagesDiv, wasScrolled: () => scrolled };
}

test('displayWebSearchResults renders linked titles + snippets (compact format)', () => {
    if (!JSDOM) return; // jsdom optional
    const dom = new JSDOM('<!doctype html><body></body>');
    global.window = dom.window; global.document = dom.window.document;
    const { fn, messagesDiv } = makeDisplayFn(dom);

    const text = [
        '1. First Source — the first snippet here',
        '   URL: https://a.test/page',
        '2. Second <Source> & "Friends" — second snippet',
        '   URL: https://b.test/'
    ].join('\n') + '\n\n[SYSTEM NUDGE]: The web search completed successfully…';

    fn('my query', text);
    const html = messagesDiv.innerHTML;
    assert.ok(html.includes('<a href="https://a.test/page"'), 'source 1 must be a real link');
    assert.ok(html.includes('<a href="https://b.test/"'), 'source 2 must be a real link');
    assert.ok(html.includes('the first snippet here'), 'snippet content must be visible (not just titles)');
    assert.ok(html.includes('second snippet'));
    // The nudge text itself must never leak into the card.
    assert.ok(!html.includes('[SYSTEM NUDGE]'));
});

test('displayWebSearchResults still parses the legacy "title (url): snippet" shape', () => {
    if (!JSDOM) return; // jsdom optional
    const dom = new JSDOM('<!doctype html><body></body>');
    global.window = dom.window; global.document = dom.window.document;
    const { fn, messagesDiv } = makeDisplayFn(dom);

    fn('legacy', 'Old Title (https://old.test/x): old snippet\n\nOther Title (https://old.test/y): other');
    const html = messagesDiv.innerHTML;
    assert.ok(html.includes('<a href="https://old.test/x"'), 'legacy entry 1 linked');
    assert.ok(html.includes('<a href="https://old.test/y"'), 'legacy entry 2 linked');
});

test('v54: displayWebSearchResults renders deep-research findings (learned content + key facts)', () => {
    if (!JSDOM) return; // jsdom optional
    const dom = new JSDOM('<!doctype html><body></body>');
    global.window = dom.window; global.document = dom.window.document;
    const { fn, messagesDiv } = makeDisplayFn(dom);

    const report = [
        'DEEP RESEARCH REPORT — "electron-builder appimage"',
        'Sources found: 2 · pages read in full: 1',
        '',
        'SOURCE 1: AppImage | electron-build',
        'URL: https://www.electron.build/docs/appimage/',
        'WHAT I LEARNED FROM THIS PAGE:',
        'AppImage is a self-contained executable that runs on most Linux distributions without installation.',
        'KEY FACTS:',
        '- No root or package manager needed to run an AppImage.',
        '',
        'SNIPPET-ONLY SOURCES (page not readable — paywall, timeout or empty body):',
        'SOURCE 2: Linux distro guide — how to install apps on Linux',
        'URL: https://distro.test/guide'
    ].join('\n') + '\n\n[SYSTEM NUDGE] This result is a DEEP RESEARCH REPORT…';

    fn('electron-builder appimage', report);
    const html = messagesDiv.innerHTML;
    assert.ok(html.includes('<a href="https://www.electron.build/docs/appimage/"'), 'read source linked');
    assert.ok(html.includes('<details'), 'learned content is in an expandable block');
    assert.ok(html.includes('AppImage is a self-contained executable that runs on most Linux distributions without installation.'), 'what was learned must be visible');
    assert.ok(html.includes('No root or package manager needed to run an AppImage.'), 'key facts rendered');
    assert.ok(html.includes('<a href="https://distro.test/guide"'), 'snippet-only source linked too');
    assert.ok(html.includes('(deep research — pages read in full)'), 'card is labeled as deep research');
});

test('displayWebSearchResults escapes HTML in titles/snippets (XSS guard)', () => {
    if (!JSDOM) return;
    const dom = new JSDOM('<!doctype html><body></body>');
    global.window = dom.window; global.document = dom.window.document;
    const { fn, messagesDiv } = makeDisplayFn(dom);

    fn('x', '1. <img src=x onerror=alert(1)> — snippet\n   URL: https://a.test/');
    assert.ok(!messagesDiv.innerHTML.includes('<img'), 'raw HTML in a title must be escaped');
});

test('displayWebSearchResults renders nothing for "No web results found"', () => {
    if (!JSDOM) return;
    const dom = new JSDOM('<!doctype html><body></body>');
    global.window = dom.window; global.document = dom.window.document;
    const { fn, messagesDiv } = makeDisplayFn(dom);

    fn('x', 'No web results found. Tell the user you could not find any results.');
    assert.equal(messagesDiv.children.length, 0);
});

// ── 3. chat loop: silent-turn nudge is bounded (no infinite "working…" spin) ───

test('silentTurns counter exists and bounds the post-tool silence loop', () => {
    // Declared before the while loop…
    const declIdx = APP_SRC.indexOf('let silentTurns = 0');
    assert.notEqual(declIdx, -1, 'silentTurns must be declared (let) in sendMessage');
    assert.ok(APP_SRC.indexOf('while (!finished)') > declIdx);

    // …incremented on a silent turn…
    const silentBranch = APP_SRC.slice(APP_SRC.indexOf('// BUG FIX: If model is silent after tool results'));
    assert.match(silentBranch, /silentTurns\+\+/);
    // …bounded at 3 with an honest end-of-run note (finished = true)…
    assert.match(silentBranch, /silentTurns >= 3/);
    const giveUpIdx = silentBranch.indexOf('silentTurns >= 3');
    // Window is generous on purpose: v53.5 inserted the web-search fallback block between the
    // counter and the give-up branch, so a tight window would fail on unrelated insertions.
    assert.ok(giveUpIdx > -1 && silentBranch.slice(giveUpIdx, giveUpIdx + 2600).includes('finished = true'), 'must END the run after 3 silent turns');
    // …and reset when a real reply lands.
    assert.match(APP_SRC, /else if \(turnCount > 1\) \{\s*silentTurns = 0/);
});

test('a streamed (non-empty) reply resets the silence counter', () => {
    const emitIdx = APP_SRC.indexOf('const emitStream');
    assert.notEqual(emitIdx, -1);
    assert.match(APP_SRC.slice(emitIdx, emitIdx + 260), /silentTurns = 0/);
});

// ── 4. Code Mode timeline: web_search shows retrieved content ──────────────────

test('activity timeline renders web_search results (not a KV dump)', () => {
    if (!JSDOM) return;
    const dom = new JSDOM('<!doctype html><body><div id="tl"></div></body>');
    global.window = dom.window; global.document = dom.window.document;

    delete require.cache[require.resolve('../src/renderer/timeline/eventAdapter.js')];
    delete require.cache[require.resolve('../src/renderer/timeline/activityTimeline.js')];
    require('../src/renderer/timeline/eventAdapter.js'); // attaches window.XKEventAdapter
    const timeline = require('../src/renderer/timeline/activityTimeline.js');

    const container = dom.window.document.getElementById('tl');
    timeline.mount(container, {});
    timeline.handleCodeEvent({ type: 'tool_start', name: 'web_search', args: { query: 'electron-builder' }, callId: 'c1' });
    timeline.handleCodeEvent({
        type: 'tool_result', name: 'web_search', ok: true, callId: 'c1', durationMs: 900,
        result: {
            results: [{ title: 'appimage | electron-builder', url: 'https://www.electron.build/docs/appimage/', snippet: 'AppImage is a self-contained…' }],
            summary: '1. appimage | electron-builder — AppImage is a self-contained…\n   URL: https://www.electron.build/docs/appimage/'
        }
    });

    const html = container.innerHTML;
    assert.ok(html.includes('AppImage is a self-contained'), 'retrieved content must be visible in the timeline');
    assert.ok(html.includes('1 source retrieved'), 'row summary counts sources');
});

test('activity timeline renders fetch_url content', () => {
    if (!JSDOM) return;
    const dom = new JSDOM('<!doctype html><body><div id="tl"></div></body>');
    global.window = dom.window; global.document = dom.window.document;
    delete require.cache[require.resolve('../src/renderer/timeline/eventAdapter.js')];
    delete require.cache[require.resolve('../src/renderer/timeline/activityTimeline.js')];
    require('../src/renderer/timeline/eventAdapter.js'); // re-bind to THIS window
    const timeline = require('../src/renderer/timeline/activityTimeline.js');

    const container = dom.window.document.getElementById('tl');
    timeline.mount(container, {});
    timeline.handleCodeEvent({ type: 'tool_start', name: 'fetch_url', args: { url: 'https://x.test' }, callId: 'c2' });
    timeline.handleCodeEvent({ type: 'tool_result', name: 'fetch_url', ok: true, callId: 'c2', durationMs: 400, result: { content: 'PAGE BODY TEXT', url: 'https://x.test', status: 200 } });

    assert.ok(container.innerHTML.includes('PAGE BODY TEXT'));
});
